---
# Calls a lazy mock build
- hosts: "{{ host | default('localhost') }}"
  become: true
  become_user: root
  gather_facts: true

  pre_tasks:
    - name: Check if ansible cannot be run here
      stat:
        path: /etc/no-ansible
      register: no_ansible

    - name: Verify if we can run ansible
      assert:
        that:
          - "not no_ansible.stat.exists"
        success_msg: "Builder is available"
        fail_msg: "Builder is unavailable"

    - name: Reset mock_builder fact
      set_fact:
        mock_builder: "{{ mock_builder | default('rpmbuild') }}"

  tasks:
    - name: Include lazybuilder mock setup tasks - NFS
      include_role:
        name: lazybuilder
        tasks_from: "wrapper/mock_setup_only_nfs.yml"
...
