---
################################################################################
# transfer wrapper, copy the files to where they need to be. another task will
# take care of the repo generation if it's required.
- name: Perform a local transfer
  block:
    - name: Identify all built RPMs
      find:
        paths: "/var/lib/mock/{{ mock_build_root }}/result"
        recurse: true
        patterns:
          - '*.rpm'
      register: result_all_build_rpms
      tags:
        - transfer

    - name: Identify all non-debug built RPMs
      find:
        paths: "/var/lib/mock/{{ mock_build_root }}/result"
        recurse: true
        patterns:
          - '*.noarch.rpm'
          - '*.{{ mock_arch }}.rpm'
        excludes:
          - "*-debuginfo-*"
          - "*-debugsource-*"
      register: result_build_rpms
      tags:
        - transfer

    - name: Identify all debug RPMs if applicable
      find:
        paths: "/var/lib/mock/{{ mock_build_root }}/result"
        recurse: true
        patterns:
          - '*-debuginfo-*'
          - '*-debugsource-*'
      register: result_debug_build_rpms
      tags:
        - transfer

    - name: Identify all build logs
      find:
        paths: "/var/lib/mock/{{ mock_build_root }}/result"
        recurse: true
        patterns: '*.log'
      register: result_build_logs
      tags:
        - transfer

    - name: Ensure all directories are setup for drop
      file:
        path: '{{ item }}'
        owner: '{{ mock_builder }}'
        group: '{{ mock_builder }}'
        mode: '0755'
        state: directory
      with_items:
        - "{{ repo_drop_path }}"
        - "{{ repo_drop_path_results }}/{{ srpm_nevra_ret.stdout }}/{{ mock_arch }}"
      tags:
        - transfer

    # There are plenty of noarch builds out there, no point in making a
    # debug directory in every instance, especially during constraints or
    # builds that are designed NOT to produce debuginfo/debugsource packages
    - name: Ensure there is a drop for debug packages
      file:
        path: '{{ item }}'
        owner: '{{ mock_builder }}'
        group: '{{ mock_builder }}'
        mode: '0755'
        state: directory
      with_items:
        - "{{ repo_drop_path }}-debug"
      when: result_debug_build_rpms.matched > 0
      tags:
        - transfer

    - name: Copy compiled RPMs into their proper spot
      copy:
        src: "{{ item.path }}"
        dest: "{{ repo_drop_path }}/"
        owner: "{{ mock_builder }}"
        mode: "0644"
        remote_src: true
      with_items: "{{ result_build_rpms.files }}"
      when: not scratch_build|bool
      tags:
        - transfer

    - name: Copy debug RPMs into their spot
      copy:
        src: "{{ item.path }}"
        dest: "{{ repo_drop_path }}-debug/"
        owner: "{{ mock_builder }}"
        mode: "0644"
        remote_src: true
      with_items: "{{ result_debug_build_rpms.files }}"
      when:
        - result_debug_build_rpms.matched > 0
        - not scratch_build|bool
      tags:
        - transfer

    - name: Copy all source RPMs into the results area
      copy:
        src: "{{ item.path }}"
        dest: "{{ repo_drop_path_results }}/{{ srpm_nevra_ret.stdout }}/{{ mock_arch }}"
        owner: "{{ mock_builder }}"
        mode: "0644"
        remote_src: true
      with_items: "{{ result_all_build_rpms.files }}"
      tags:
        - transfer

    - name: Copy build logs into the results area
      copy:
        src: "{{ item.path }}"
        dest: "{{ repo_drop_path_results }}/{{ srpm_nevra_ret.stdout }}/{{ mock_arch }}"
        owner: "{{ mock_builder }}"
        mode: "0644"
        remote_src: true
      with_items: "{{ result_build_logs.files }}"
      tags:
        - transfer

    - name: Copy mock configs
      copy:
        src: "{{ item }}"
        dest: "{{ repo_drop_path_results }}/{{ srpm_nevra_ret.stdout }}/{{ mock_arch }}"
        owner: "{{ mock_builder }}"
        mode: "0644"
        remote_src: true
      with_items:
        - '/home/{{ mock_builder }}/mock-wrapper.sh'
        - '/home/{{ mock_builder }}/{{ distro }}-{{ major }}-{{ mock_arch }}.cfg'
      tags:
        - transfer

    - name: Ensure fail file doesn't exist
      file:
        path: "{{ repo_drop_path_results }}/{{ srpm_nevra_ret.stdout }}/{{ mock_arch }}/failed"
        state: absent
      tags:
        - transfer

  rescue:
    - name: We failed, display the error.
      debug:
        msg: "Failed to copy or setup dropbox: {{ ansible_failed_result }}"

    - name: Perform full cleanup
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - '{{ mock_builder_rpmbuild_dir }}'
        - '{{ mock_builder_source_dir }}'
        - '/home/{{ mock_builder }}/mock-wrapper.sh'
        - '/home/{{ mock_builder }}/{{ distro }}-{{ major }}-{{ mock_arch }}.cfg'
        - '{{ mock_builder_module_dir }}'
        - '{{ repo_drop_path_results }}'
      when:
        - enable_cleanup|bool

    - name: System is no longer in use
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - "/var/tmp/.build_in_progress"

    - name: Fail when there's an error in the block
      fail:
        msg: "Exiting entire play"

  when:
    - (repo_host == "localhost") or (transfer_type == "nfs")
    - not module_mode|bool
  tags:
    - transfer

- name: Perform a non-local transfer
  block:
    - name: Not supported
      debug:
        msg:
          - "!! This method is not supported"
          - "This method of transport will likely not be supported in the"
          - "future. If you need remote transfers, you may need to build your"
          - "playbooks to support such transfers."

    - name: Ending
      fail:
        msg: "Exiting entire play"
  when:
    - (not repo_host == "localhost") and (not transfer_type == "nfs")
  tags:
    - transfer
...
