---
################################################################################
# Check that mock_srpm_path is defined
- name: Check mock_srpm_path
  block:
    - name: Verify that that the srpm path is defined and is a src file
      assert:
        that:
          - mock_srpm_path is defined
          - '"src.rpm" in mock_srpm_path'
        fail_msg: |
          - "The path to the srpm was not defined."
          - "Did you properly pull it or build it from source?"
        success_msg: "mock_srpm_path is properly defined as {{ mock_srpm_path }}"
      when: not module_mode|bool
      tags:
        - mock
        - build_phase

    - name: Verify that that the srpm path is defined and is a list
      assert:
        that:
          - mock_srpm_path is defined
          - mock_srpm_path is iterable and (mock_srpm_path is not string and mock_srpm_path is not mapping)
        fail_msg: |
          - "mock_srpm_path is not a list"
        success_msg: "mock_srpm_path is properly defined as {{ mock_srpm_path }}"
      when: module_mode|bool
      tags:
        - mock
        - module
        - build_phase
  rescue:
    - name: We failed, display the error.
      debug:
        msg: "Failed to build our RPM: {{ ansible_failed_result }}"

    - name: Perform full cleanup
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - '{{ mock_builder_rpmbuild_dir }}'
        - '{{ mock_builder_source_dir }}'
        - '/home/{{ mock_builder }}/mock-wrapper.sh'
        - '/home/{{ mock_builder }}/{{ distro }}-{{ major }}-{{ mock_arch }}.cfg'
        - '/home/{{ mock_builder }}/module'
      when:
        - enable_cleanup|bool

    - name: System is no longer in use
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - "/var/tmp/.build_in_progress"

    - name: Fail when there's an error in the block
      fail:
        msg: "Exiting entire play"

################################################################################
# perform the build - the RPMs made will be put into a var
- name: Build Process
  block:
    - name: Display vars
      debug:
        msg:
          - "Name: {{ mock_vendor }}"
          - "Version: {{ full }}"
          - "Dist tag: {{ mock_combined_dist }} {{ module_dist | default('') }}"
          - "Source: {{ source_name }} {{ mock_srpm_path }}"
          - "Architecture: {{ mock_arch }}"
          - "Module: {{ module_mode }}"
      tags:
        - mock
        - build_phase

    ############################################################################
    # Mock config file that will control the build
    - name: "Deploy mock config file"
      template:
        src: "mock/mock.cfg.j2"
        dest: "/home/{{ mock_builder }}/{{ distro }}-{{ major }}-{{ mock_arch }}.cfg"
        owner: "{{ mock_builder }}"
        group: "{{ mock_builder }}"
        mode: "0644"
      tags:
        - mock
        - build_phase

    ############################################################################
    # Mock wrapper that calls the config deployed
    - name: Deploy mock build script
      template:
        src: "mock/mock-wrapper.sh.j2"
        dest: "/home/{{ mock_builder }}/mock-wrapper.sh"
        owner: "{{ mock_builder }}"
        group: "{{ mock_builder }}"
        mode: "0755"
      tags:
        - mock
        - build_phase

    ############################################################################
    # Runs the mock build
    - name: Mark system as in use
      file:
        path: "/var/tmp/.build_in_progress"
        state: touch
        mode: "0644"
      tags:
        - mock
        - build_phase

    - name: Notification of build start
      debug:
        msg: "Starting/continuing build for {{ source_name }}"
      tags:
        - mock
        - build_phase

    - name: Run the mock build
      command:
        cmd: "/home/{{ mock_builder }}/mock-wrapper.sh"
        chdir: "/home/{{ mock_builder }}"
      register: mock_finish
      changed_when: "1 != 1"
      ignore_errors: true
      tags:
        - mock
        - build_phase

    - name: Identify all built RPMs post-build
      find:
        paths: "/var/lib/mock/{{ mock_build_root }}/result"
        recurse: true
        patterns:
          - '*.rpm'
      register: mock_built_rpms
      tags:
        - transfer

    ############################################################################
    # Verify that mock exited cleanly.
    - name: Check that mock exited cleanly
      assert:
        that:
          - mock_finish.rc == 0
          # (mock_finish.rc == 0) or (mock_built_rpms.matched > 0)
        fail_msg:
          - "=========================================================================="
          - "Mock did not exit cleanly - build likely failed"
          - "Please verify the logs on {{ ansible_hostname }} in:"
          - "/var/lib/mock/{{ mock_build_root }}/result"
        success_msg:
          - "Mock build succeeded"
          - "Results: /var/lib/mock/{{ mock_build_root }}/result"
          - "!! NOTE !!"
          - "If transfer mode is enabled, these RPMs will be copied appropriately."
      tags:
        - mock
        - build_phase
  rescue:
    - name: We failed, display the error.
      debug:
        msg:
          - "Failed to build our RPM: {{ ansible_failed_result }}"

    - name: Perform full cleanup
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - '{{ mock_builder_rpmbuild_dir }}'
        - '{{ mock_builder_source_dir }}'
        - '/home/{{ mock_builder }}/mock-wrapper.sh'
        - '/home/{{ mock_builder }}/{{ distro }}-{{ major }}-{{ mock_arch }}.cfg'
        - '/home/{{ mock_builder }}/module'
      when:
        - enable_cleanup|bool

    - name: System is no longer in use
      file:
        path: '{{ item }}'
        state: absent
      loop:
        - "/var/tmp/.build_in_progress"

    # This only works for single builds for now
    - name: Drop path should exist for the failure
      file:
        path: '{{ item }}'
        owner: '{{ mock_builder }}'
        group: '{{ mock_builder }}'
        mode: '0755'
        state: directory
      loop:
        - "{{ repo_drop_path }}"
        - "{{ repo_drop_path_results }}/{{ srpm_nevra_ret.stdout }}/{{ mock_arch }}"

    - name: Drop fail file
      file:
        path: "{{ repo_drop_path_results }}/{{ srpm_nevra_ret.stdout }}/{{ mock_arch }}/failed"
        state: touch

    - name: Identify all build logs
      find:
        paths: "/var/lib/mock/{{ mock_build_root }}/result"
        recurse: true
        patterns: '*.log'
      register: result_fail_build_logs
      tags:
        - transfer

    - name: Copy build logs into the results area for failure
      copy:
        src: "{{ item.path }}"
        dest: "{{ repo_drop_path_results }}/{{ srpm_nevra_ret.stdout }}/{{ mock_arch }}"
        owner: "{{ mock_builder }}"
        mode: "0644"
        remote_src: true
      with_items: "{{ result_fail_build_logs.files }}"
      tags:
        - transfer

    - name: Tell user where to find the logs
      debug:
        msg: "Logs are located: {{ repo_drop_path_results }}/{{ srpm_nevra_ret.stdout }}/{{ mock_arch }}"

    - name: Fail when there's an error in the block
      fail:
        msg: "Exiting entire play"
...
