---
################################################################################
# Verify certain things are not default
- name: "Verify that our source_name is not defaulted as name"
  assert:
    that:
      - source_name != "name"
    fail_msg: "You cannot use the default source_name: {{ source_name }}"
    success_msg: "Our source_name is defined as: {{ source_name }}"
  tags:
    - mock

- name: "Verify that build mode is mock"
  assert:
    that:
      - build_mode == "mock"
    fail_msg: "Build mode is not set to mock."
    success_msg: "We are in mock mode."
  tags:
    - mock

################################################################################
# Verify invalid configurations
- name: "Fail if module_mode and constraint is on"
  fail:
    msg: "You cannot have module mode and constraint on at the same time"
  when:
    - module_mode|bool
    - sig_or_constraint|bool

################################################################################
# Are we able to run on this builder? Is it busy?

- name: Check for metadata file
  stat:
    path: "/var/tmp/.build_in_progress"
  register: in_progress_check
  check_mode: false
  changed_when: "1 != 1"
  tags:
    - mock

- name: "Verify that a build is not already in process"
  assert:
    that:
      - not in_progress_check.stat.exists
    fail_msg: "A build is likely already in progress on this host."
  tags:
    - mock

################################################################################
# Start simple vars
- name: "Set simplification vars"
  set_fact:
    mock_builder_rpmbuild_dir: "/home/{{ mock_builder }}/rpmbuild"
    mock_builder_source_dir: "/home/{{ mock_builder }}/{{ source_name }}"
    mock_builder_module_dir: "/home/{{ mock_builder }}/module"
    mock_combined_dist: "{{ mock_dist | default(dist) }}{{ mock_dist_append | default('') }}"
  tags:
    - mock
# End simple vars
################################################################################

################################################################################
# Start imports
- name: "Import el{{ major }} repos for {{ distro }} if available"
  include_vars: "{{ mock_el_repo_config }}"
  when:
    - not bootstrap|bool
    - not internal_buildsys|bool
  tags:
    - mock

- name: "Import module data for el{{ major }}"
  include_tasks: "../module/data_import.yml"
  when:
    - module_mode|bool
  tags:
    - mock
    - module

- name: "Import arch data"
  include_vars: "arch/{{ mock_arch }}.yml"
  tags:
    - mock
# End
################################################################################

################################################################################
# Setting base line facts for mock and transfer directories
- name: "Make our mock dir for http"
  set_fact:
    mock_repo_path: "{{ mock_http_repo_path }}"
  when:
    - mock_use_http_path
  tags:
    - mock

- name: "Make our mock dir for file"
  set_fact:
    mock_repo_path: "{{ mock_file_repo_path }}"
  when:
    - mock_use_file_path
  tags:
    - mock

- name: "Set all relevant mock repo path facts even if some aren't used"
  set_fact:
    mock_solo_full_path: "{{ mock_repo_path }}/{{ major }}-{{ mock_solo_name }}-{{ mock_arch }}"
    mock_bs_full_path: "{{ mock_repo_path }}/{{ major }}-{{ mock_bootstrap_name }}-{{ mock_arch }}"
    mock_default_full_path: "{{ mock_repo_path }}/{{ major }}-{{ mock_repo_name }}-{{ mock_arch }}"
    repo_drop_path_results: "{{ repo_path }}/results/{{ source_name }}"
  tags:
    - mock

- name: "Set relevant dropbox path - Default"
  set_fact:
    repo_drop_path: "{{ mock_default_path }}"
    #repo_drop_path_results: "{{ repo_path }}/results/{{ source_name }}"
  when:
    - not module_mode|bool
    - not bootstrap|bool
    - not sig_or_constraint|bool
  tags:
    - mock

- name: "Set relevant dropbox path - Bootstrap"
  set_fact:
    repo_drop_path: "{{ mock_bootstrap_path }}"
    #repo_drop_path_results: "{{ repo_path }}/bootstrap-results/{{ source_name }}"
  when:
    - not module_mode|bool
    - bootstrap|bool
    - not sig_or_constraint|bool
  tags:
    - mock

- name: "Set relevant dropbox path - Constraint"
  set_fact:
    repo_drop_path: "{{ mock_solo_path }}"
    repo_drop_path_results: "{{ repo_path }}/solo-results/{{ source_name }}"
  when:
    - not module_mode|bool
    - not bootstrap|bool
    - sig_or_constraint|bool
  tags:
    - mock

- name: "Set relevant dropbox path - Module"
  set_fact:
    repo_drop_path: "{{ repo_path }}/module-repos/{{ module_format }}-{{ module_context }}-{{ mock_arch }}"
    repo_drop_path_results: "{{ repo_path }}/module-results/{{ mock_arch }}/{{ source_name }}-{{ module_data.data.stream }}-{{ module_version }}"
    repo_drop_path_results_root: "{{ repo_path }}/module-results"
  when:
    - module_mode|bool
    - not sig_or_constraint|bool
  tags:
    - mock

- name: "Reset dropbox results if this is a scratch build"
  set_fact:
    repo_drop_path_results: "{{ repo_path }}/scratch-results/{{ source_name }}/{{ '%Y%m%d%H%M%S' | strftime(ansible_date_time.epoch) }}"
  when:
    - scratch_build|bool
    - not module_mode|bool
  tags:
    - mock

- name: "Reset dropbox results if this is a chain build only"
  set_fact:
    repo_drop_path_results: "{{ repo_path }}/results"
  when:
    - not scratch_build|bool
    - not module_mode|bool
    - not sig_or_constraint|bool
    - mock_chain|bool
  tags:
    - mock

# End
################################################################################

################################################################################
# Import other repo stuff now that facts are in alignment
- name: "Import el{{ major }} sig or req constraint repos"
  include_vars: "{{ mock_solo_repo_config }}"
  when:
    - not bootstrap|bool
    - sig_or_constraint|bool
  tags:
    - mock

- name: "Import el{{ major }} bootstrap repos"
  include_vars: "{{ mock_bs_repo_config }}"
  when:
    - bootstrap|bool
    - not internal_buildsys|bool
  tags:
    - mock

- name: "Import only el{{ major }} bootstrap/buildsys repos"
  include_vars: "{{ mock_buildsys_repo_config }}"
  when:
    - internal_buildsys|bool
  tags:
    - mock

- name: "Import epel {{ major }} repos"
  include_vars: "el/epel.yml"
  when:
    - enable_epel|bool
  tags:
    - mock

- name: "Import rpmfusion el{{ major }} repos"
  include_vars: "el/rpmfusion.yml"
  when:
    - enable_rpmfusion|bool
  tags:
    - mock

# End
################################################################################
...
