---
mock_repos:
  - repoid: "baseos"
    baseurl: "https://dl.rockylinux.org/pub/rocky/{{ major }}/BaseOS/{{ mock_arch }}/os"
    gpgcheck: 1
    enabled: 1
    gpgkey: file:///usr/share/distribution-gpg-keys/rocky/RPM-GPG-KEY-rockyofficial
  - repoid: "appstream"
    baseurl: "https://dl.rockylinux.org/pub/rocky/{{ major }}/AppStream/{{ mock_arch }}/os"
    gpgcheck: 1
    enabled: 1
    gpgkey: file:///usr/share/distribution-gpg-keys/rocky/RPM-GPG-KEY-rockyofficial
  - repoid: "powertools"
    baseurl: "https://dl.rockylinux.org/pub/rocky/{{ major }}/PowerTools/{{ mock_arch }}/os"
    gpgcheck: 1
    enabled: 1
    gpgkey: file:///usr/share/distribution-gpg-keys/rocky/RPM-GPG-KEY-rockyofficial
  - repoid: "devel"
    baseurl: "https://dl.rockylinux.org/pub/rocky/{{ major }}/Devel/{{ mock_arch }}/os"
    gpgcheck: 1
    enabled: "{% if enable_devel is defined and enable_devel|bool %}1{% else %}0{% endif %}"
    gpgkey: file:///usr/share/distribution-gpg-keys/rocky/RPM-GPG-KEY-rockyofficial
mock_chroot_setup_cmd: "install tar gcc-c++ redhat-rpm-config redhat-release which xz sed make bzip2 gzip gcc coreutils unzip shadow-utils diffutils cpio bash gawk rpm-build info patch util-linux findutils grep"
...
