---
# General vars that are usable across all modes
# These vars should NOT be overridden
mock_srpm_names: []
sum_lengths:
  sum_length_32: "md5"
  sum_length_40: "sha1"
  sum_length_56: "sha224"
  sum_length_64: "sha256"
  sum_length_96: "sha384"
  sum_length_128: "sha512"
...
