---
# defaults file for lazybuilder
major: 8
minor: 5
# only needed if using centos as a bootstrap
year_month: 2111
full: "{{ major }}.{{ minor }}"
# this can be a source rpm name or a module name
source_name: name
# Override this with a mock_dist var
dist: "el{{ major }}"
distro: "rocky"
enable_cleanup: true
system_requires_init: false
# This needs to be set explicitly and the right build host will need to be
# picked from the inventory. There is logic in the tasks that will actually
# stop everything if the mock_arch and the architecture fact do falset match.
# Current valid arches: x86_64 | i686 | ppc64le | aarch64
mock_arch: "x86_64"
mock_vendor: "Rocky"
mock_packager: "Lazy Builder <releng@rockylinux.org>"
mock_multilib: false
# This is the user that will be configured to run mock builds
mock_builder: "rpmbuild"
mock_rpmbuild_networking: "False"
mock_use_host_resolv: "False"
mock_build_root: "{{ distro }}-{{ major }}-{{ mock_arch }}"
# This is if you want to chain builds. Set mock_chain_list to the list of
# packages you want to build in a chain or ensure srpm_url is a list of
# source RPM url's to download.
mock_chain: false
mock_chain_recurse: false
# mock_chain_list: []
# chain_git_url: https://git.rockylinux.org/staging/rpms
mock_quiet: false
# If a special piece needs to be added to a release tag, use this var by
# defining it in a playbook. Examples below (commented)
#mock_dist_append: ".{{ distro }}.0"
#mock_dist_append: ".0"
#mock_dist_append: ".sig.0"
# If you need extra rpmbuild options, make a list.
# mock_rpmbuild_opts
# If you need a timeout on rpmbuilds, set it (in seconds)
# mock_rpmbuild_timeout
# If you need extra macros, set it here as a literal (|) multi-line block
# mock_rpmbuild_macro_set

# The following is not implemented yet
# If you need to set with/without conditions, set them as a list
# mock_with_opts
# mock_without_opts
# If you need extra options given to mock directly, put them as a full string
# mock_extra_opts

# modes
# mock is the only accepted option as of this public release
build_mode: mock
module_mode: false
scratch_build: false

# transfer mode settings
repo_host: localhost
# nfs|sync|copy
transfer_type: copy
# this has no effect if we are bootstrapping - bootstraps automatically make
# repos
generate_repo: "false"

# module mode settings
module_tracker: file
# This is module version we'll assume. For example, module version 2 is used in
# el8. el9 it may or may not change. It hasn't changed in Fedora. Assuming this
# project continues to be maintained, we'll need to be ready for future
# versions or changes.
module_version_type: "2"

# Generally, the MBS service will auto-generate a macros rpm (annoying or not,
# this is what it does). We don't want to do that, so some of our stuff will be
# here, other stuff will be in other vars or templates.
# module_stream: "1.0"
module_version: "{{ major }}0{{ minor }}00{{ '%Y%m%d%H%M%S' | strftime(ansible_date_time.epoch) }}"
# module_module_name: "{{ source_name }}"
# This needs to be a URL to a git project that will be cloned. The commit can be a
# hash or branch name - If main is used, play will end. This will override the
# git mode section's commit hash.
# There are two places a module yaml could be located, directly from a web URL
# or from git. We want to provide both options. Default is git and the module
# yaml is expected to be at the root of the repo with the same name as
# source_name.
#
# There may be occassions where older versions of a module may need to be
# built. That option is offered by setting module_git_branch to the commit hash
# in the appropriate git repo. Set module_follow_refs to true, and the
# commit hashes/references of the YAML will be followed to each package.
#
# The commented vars are examples.
#
module_yaml_location_type: git
# module_git_url: https://git.rockylinux.org/staging/rpms
# module_git_repo: https://git.rockylinux.org/staging/modules/{{ source_name }}.git
# module_git_branch: "r{{ major }}-stream-version"
# module_defaults_git_repo: https://git.rockylinux.org/rocky/rocky-module-defaults.git
# module_defaults_git_branch: "r{{ full }}"
# module_yaml_http_url: https://example.rockylinux.org/{{ source_name }}.yaml
# module_defaults_yaml_http_url: https://example.rockylinux.org/{{ source_name }}.yaml
module_follow_refs: true

# There are some cases where we need to ask for a module to be enabled in the
# first place. You will need to create a list, sort of like this:
# module_setup_commands:
#   idm: "disable"
#   idm:DL1: "enable"
#
# However, there are module builds that will need the above no matter what. So
# instead of defining the above manually for a module build, keep the below set
# to true, so that way the buildrequires are properly determined.
module_needs_modules: true
# Some modules are virtual modules, meaning they do not have a module dist, but
# are still part of a module. The yamls they are built from do not have a list
# of buildable components. Instead they are built normally and a YAML is
# inserted after the fact to enable the module. Set this to true to generate
# a standard YAML with no components. This can also be useful to generate/test
# YAML creation for modules.
module_no_components: false

# build mode settings
# isolation modes are auto|nspawn|simple
# it is recommended to use simple when building kernels for EL or when building
# in a container
mock_isolation: auto
bootstrap: false
sig_or_constraint: false
internal_buildsys: false
# This turns on the devel repository - User takes responsibility for the use of
# this repository
enable_devel: false
# This turns on EPEL repositories
# Turn on modular by setting to true as needed
enable_epel: false
enable_epel_modular: false
# This turns on RPMFusion repositories - enable_rpmfusion only enables the free
# repository. Turn on nonfree by setting to true as needed.
enable_rpmfusion: false
enable_rpmfusion_nonfree: false
# Disable test checking - This turns on --nocheck and --without=tests
# Note that this disables the commonly used macros, so some tests may still end
# up running
disable_tests: false
# override/overwrite packages?
override_package: false
# This tells us where the repos (relative to the filesystem on the repo box) is
# located. Repos will be in subdirectories under here (including for modules).
# Expect that it will look sort of like: /opt/repo/lazystrap
repo_path: "/opt/repo"
repo_result_root: "{{ repo_path }}/results"
# This is the file URL to the repo store if the builder is using repos locally.
# It will combined to look sort of like: file:///opt/repo/lazystrap
mock_file_repo_path: "file://{{ repo_path }}"
# This is the http URL to the repo store if the builder is using a remote repo.
# Note that you have to be precise, because the repo_path and the path on the
# remote machine (as presented by the web service) can be different. In the
# tasks, there are pieces that combine this (or the file one) together to make
# a full repo path. For example, http://repo.example.com/repo/solostrap
mock_http_repo_path: "http://repo.example.com/repo"
# Below are names that'd be names of repos. However, do NOT expect that to be
# the actual name. Expect this format: 8-name-arch
# This is just a repo name - This is used if bootstrap or constraint is false,
# and mock_repo_name is undefined
mock_repo_name: "default"
# This just names the bootstrap repo and directory. Nothing special.
mock_bootstrap_name: "lazystrap"
# This just names the solo repo and directory. Nothing special. Used for sigs
# or specialty builds.
mock_solo_name: "solostrap"
mock_default_path: "{{ repo_path }}/{{ major }}-{{ mock_repo_name }}-{{ mock_arch }}"
mock_bootstrap_path: "{{ repo_path }}/{{ major }}-{{ mock_bootstrap_name }}-{{ mock_arch }}"
mock_solo_path: "{{ repo_path }}/{{ major }}-{{ mock_solo_name }}-{{ mock_arch }}"

# These control some of the above
mock_use_http_path: false
mock_use_file_path: true

# This sets default yaml conf files which can be overridden - lazybuilder by
# default uses rocky repos when doing builds. When buildsys is on or bootstrap
# modes are on, this isn't typically used. This means that mock_repos can just
# be overridden or even added in other ways if not turned on.
#
# Note: While it is possible to override the other configs, it may just be
# simpler to import your own vars for the repo types. As of now, it's not at
# all supported and I won't address issues pertaining to it.
mock_el_repo_config: "el/el{{ major }}.yml"
mock_solo_repo_config: "el/el_solo.yml"
mock_bs_repo_config: "el/el{{ major }}_bootstrap.yml"
mock_buildsys_repo_config: "el/el_buildsys.yml"

# source settings
# This tells the mock builder how to pull together the source rpm, whether from
# a srpm, a git repo, in combination of rpkg, a lookaside repo, among other
# things. Note that rpkg and scm use mock options directly.
# Accepted answers: git|srpm|scm
source_mode: "git"
################################################################################
# git mode
#
# git_use_metadata -> Set this to true to use the metadata files. It is currently
#                     recommended that this ALWAYS be set to true.
# git_url -> Set this to the URL of the git repo. Example expected format:
#            https://git.example.com/rpms/something.git
#            When using module mode, it is better to provide it a just the group
#            name where it can reasonably find the next package to build. It will
#            autofill, eg git.example.com/rpms/package_a.git - The same applies
#            when using mock_chain
# git_source_url -> Set this to the lookaside cache that is generally a web URL
#                   This place where the archives sit should be named of the 
#                   sha*sum of the file. Original archive name is NOT supported.
# git_commit -> The full commit hash, otherwise the branch "main" will be used
#               Note that if the git_url is in a format that has the git commit
#               hash in it, it will be split properly and git_commit will be
#               overridden automatically in the play.
#               Eg: http://git/rpms/name.git?HASH
#               Eg: git+https://git/rpms/name.git?HASH
#               Eg: git+https://git/rpms/name.git#?HASH
#               When using module mode, it is better that this is a branch name
#               that identifies what is being used. Some packages have a normal
#               branch for non-module builds and also module branches. It should
#               be guaranteed that module packages (and the module repo itself)
#               all share the same branch name.
#               Even though you may set this, it will be overriden.
git_use_metadata: true
# git_url: ...
# git_source_url: ...
# git_commit: ...
# Source RPM url - This is a simple URL to where an SRPM is located. Must be
# http or https
# srpm_url: ...
################################################################################
# scm mode
# (No options yet)
################################################################################
# rpkg settings
# (No options yet)
...
